[package]
name = "express-relay-decoder"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-sdk = "1.18.26"
borsh = "0.10.3"
borsh-derive = "0.10.3"

anchor-decoder = { path = "../../crates/anchor-decoder" }
